CREATE TABLE parking_bay_detail(
    PARKING_BAY_NAME TEXT NOT NULL,
    PARKING_BAY_STATUS INT NOT NULL
);

CREATE TABLE parking_bay_timestamp(
    PARKING_BAY_ID INT NOT NULL,
    PARKING_BAY_ENTRY_TIME DATETIME NOT NULL,
    PARKING_BAY_EXIT_TIME DATETIME,
    PARKING_BAY_TOTAL_MINUTES INT
);