INSERT INTO parking_bay_detail (PARKING_BAY_NAME,PARKING_BAY_STATUS)
VALUES ('A1', 0);

INSERT INTO parking_bay_detail (PARKING_BAY_NAME,PARKING_BAY_STATUS)
VALUES ('A2', 0);

INSERT INTO parking_bay_detail (PARKING_BAY_NAME,PARKING_BAY_STATUS)
VALUES ('A3', 2);